

[package]
name = "vrl"
workspace = "../workspace"
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
autobins = false
autoexamples = false
autotests = false
autobenches = false


[lib]
name = "vrl"
path = "./lib.rs"
test = false
bench = false
doctest = false


[features]
default = []
all = [
	"bytes",
	"cli-arguments",
	"errors",
	"experiments",
	"preludes",
	"random",
]
bytes = ["vrl-bytes"]
cli-arguments = ["vrl-cli-arguments"]
errors = ["vrl-errors"]
experiments = ["vrl-experiments"]
preludes = ["vrl-preludes"]
random = ["vrl-random"]


[dependencies]
vrl-bytes = { path = "../bytes", optional = true, default-features = false, features = ["all"] }
vrl-cli-arguments = { path = "../cli-arguments", optional = true, default-features = false, features = ["all"] }
vrl-errors = { path = "../errors", optional = true, default-features = false, features = ["all"] }
vrl-experiments = { path = "../experiments", optional = true, default-features = false, features = ["all"] }
vrl-preludes = { path = "../preludes", optional = true, default-features = false, features = ["all"] }
vrl-random = { path = "../random", optional = true, default-features = false, features = ["all"] }


