

################################################################################
################################################################################




[workspace]

members = [
	"../bytes",
	"../cli-arguments",
	"../errors",
	"../experiments",
	"../lib",
	"../preludes",
	"../random",
]

resolver = "3"




################################################################################
################################################################################




[workspace.package]

version = "0.1.0"
publish = false

edition = "2024"
rust-version = "1.85"

authors = [
	"Ciprian Dorin Craciun <ciprian@volution.ro>",
]
license = "GPL-3.0-or-later"

description = "VRL -- Volution Rust Libraries"
keywords = []
categories = []

homepage = "https://github.com/volution/volution-rust-libraries"
repository = "https://github.com/volution/volution-rust-libraries"
documentation = "https://github.com/volution/volution-rust-libraries"




################################################################################
################################################################################




[workspace.dependencies.vrl-bytes]
version = "*"
default-features = false
path = "../bytes"

[workspace.dependencies.vrl-cli-arguments]
version = "*"
default-features = false
path = "../cli-arguments"

[workspace.dependencies.vrl-errors]
version = "*"
default-features = false
path = "../errors"

[workspace.dependencies.vrl-experiments]
version = "*"
default-features = false
path = "../experiments"

[workspace.dependencies.vrl-preludes]
version = "*"
default-features = false
path = "../preludes"

[workspace.dependencies.vrl-random]
version = "*"
default-features = false
path = "../random"


[workspace.dependencies]
anyhow = { version = "^1.0", default-features = false }
brotli = { version = "^7.0", default-features = false }
byteorder = { version = "^1.5", default-features = false }
paste = { version = "^1.0", default-features = false }
rand = { version = "^0.9", default-features = false }




################################################################################
################################################################################




[patch.crates-io]




################################################################################
################################################################################




[profile.dev]
incremental = true
codegen-units = 1024
opt-level = 1
lto = "off"
debug = "full"
debug-assertions = true
overflow-checks = true
strip = "none"
split-debuginfo = "packed"
rpath = false
panic = "unwind"


[profile.test]
incremental = true
codegen-units = 1024
opt-level = 1
lto = "off"
debug = "full"
debug-assertions = true
overflow-checks = true
strip = "none"
rpath = false
split-debuginfo = "packed"


[profile.release]
incremental = false
codegen-units = 1
opt-level = 3
lto = "fat"
debug = "none"
debug-assertions = false
overflow-checks = true
strip = "symbols"
split-debuginfo = "packed"
rpath = false
panic = "abort"


[profile.bench]
incremental = false
codegen-units = 1
opt-level = 3
lto = "fat"
debug = "none"
debug-assertions = false
overflow-checks = true
strip = "symbols"
split-debuginfo = "packed"
rpath = false




[profile.dev.package."*"]
incremental = true
codegen-units = 1024
opt-level = 1
debug = "full"
debug-assertions = true
overflow-checks = true
strip = "none"
split-debuginfo = "packed"




[profile.dev.build-override]
incremental = true
codegen-units = 1024
opt-level = 2
debug = "full"
debug-assertions = true
overflow-checks = true
strip = "none"
split-debuginfo = "packed"


[profile.release.build-override]
incremental = true
codegen-units = 1024
opt-level = 2
debug = "none"
debug-assertions = false
overflow-checks = true
strip = "symbols"
split-debuginfo = "packed"




################################################################################
################################################################################



